# Generated by Django 5.0.2 on 2024-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl_bags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
